#
version: '3.1'

networks:
  default:
    internal: true
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true

services:
  keycloak:
    image: gerzhan/moneyfan-keycloak:latest
    container_name: keycloak
    #ports:
    #  - "9080:8080"
    #  - "7443:8443"
    networks:
      - traefik
    command: "start --optimized --proxy edge"
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME:-moneyfan}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB_SCHEMA=${KC_DB_SCHEMA:-keycloak}
      - KC_HOSTNAME=sso.${DNS_DOMAIN}
      - KC_PROXY=${KC_PROXY:-edge}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
    labels:
      - traefik.enable=true
      - traefik.http.routers.moneyfan-keycloak.entrypoints=web,websecure
      - traefik.http.routers.moneyfan-keycloak.rule=Host(`sso.${DNS_DOMAIN}`)
      - traefik.http.routers.moneyfan-keycloak.service=moneyfan-keycloak-service
      - traefik.http.routers.moneyfan-keycloak.tls=true
      - traefik.http.routers.moneyfan-keycloak.tls.certresolver=production
      - traefik.http.services.moneyfan-keycloak-service.loadbalancer.server.port=8080
